{% set name = "tf2-gnn" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tf2_gnn-{{ version }}.tar.gz
  sha256: c1579f67ba671bc4b711199f77a79003828b54b9c519e6c872c7e07345f96cb5

build:
  entry_points:
    - tf2_gnn_train = tf2_gnn.cli.train:run
    - tf2_gnn_test = tf2_gnn.cli.test:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tensorflow >=2.0.0
    - dpu-utils >=0.2.7
    - h5py
    - packaging

test:
  imports:
    - tf2_gnn
  commands:
    - pip check
    - tf2_gnn_train --help
    - tf2_gnn_test --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/tf2-gnn/
  summary: TensorFlow 2.0 implementation of Graph Neural Networks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
