{% set name = "tf2-gnn" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tf2_gnn-{{ version }}.tar.gz
  sha256: c1579f67ba671bc4b711199f77a79003828b54b9c519e6c872c7e07345f96cb5

build:
  entry_points:
    - tf2_gnn_train = tf2_gnn.cli.train:run
    - tf2_gnn_test = tf2_gnn.cli.test:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - tensorflow >=2.0.0
    - dpu-utils >=0.2.7
    - h5py

test:
  imports:
    - tf2_gnn
  commands:
    - pip check
    - tf2_gnn_train --help
    - tf2_gnn_test --help
  requires:
    - pip

about:
  home: https://github.com/microsoft/tf2-gnn/
  summary: TensorFlow 2.0 implementation of Graph Neural Networks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
